name: utsmobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.1
  flutter_native_splash: ^1.1.5+1
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  # flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove
  color: "#303030"
  android: true
  web: true
  image: assets/logo/splash.png


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/gif/
    - assets/img/
    - assets/icons/
    - assets/markdown/
